### ISSUE TITLE
kvproxy编译安装依赖环境

### ISSUE THREAD

**Issue by netemu** [exinnet/kvproxy#2]
我系统环境是CentOS 6.5 x86_64
执行make后
是在编译gperftools时，会提示aclocal-1.13找不到，我个人理解和解决办法如下：
个人觉得kvproxy在CentOS 6.x上安装时需要更新autoconf 和automake
autoconf版本>2.65
automake版本>1.13
我是编译安装autoconf 2.69以及automake 1.13.4之后，再make kvproxy，再没任何错误
建议大拿能够支持make clean操作

**Comment by exinnet** [comment]
感谢你的反馈。
目前发布的0.1版本中已经支持 make clean 和 make install 。
具体的你可以看下根目录下的 Makefile文件。
make install时默认是安装到/usr/local/kvproxy。
如果想更改安装路径，可以修改下根目录下的 Makefile文件的第一行
PREFIX=/usr/local/kvproxy。
